---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[scpr-apps::default]
    attributes:
      scpr_apps:
        consul:
          service_mode: bootstrap
        config:
          scprv4:
            test:
              roles:    ['web','worker']
              hostname: scprv4.kitchen
  - name: streammachine
    run_list:
      - recipe[scpr-apps::default]
    attributes:
      scpr_apps:
        consul:
          service_mode: bootstrap
        config:
          streammachine:
            test:
              roles:    ['master','slave']
  - name: projects
    run_list:
      - recipe[scpr-apps::default]
    attributes:
      scpr_apps:
        consul:
          service_mode: bootstrap
        config:
          projects:
            test:
              roles:    ['web']
              hostname: "projects.scpr.org"
