---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: "12.2.1"

platforms:
  - name: ubuntu-12.04

suites:
  - name: scprv4
    run_list:
      - recipe[scpr-apps::default]
    attributes:
      consul:
        service_mode: bootstrap
      scpr_apps:
        nfs_enabled: false
        config:
          scprv4:
            test:
              roles:    ['web','worker']
              hostname: scprv4.kitchen
  - name: streammachine
    run_list:
      - recipe[scpr-apps::default]
    attributes:
      consul:
        service_mode: bootstrap
      scpr_apps:
        config:
          streammachine:
            test:
              roles:    ['master','slave']
  - name: projects
    run_list:
      - recipe[scpr-apps::default]
    attributes:
      consul:
        service_mode: bootstrap
      scpr_apps:
        config:
          projects:
            test:
              roles:    ['web']
              hostname: "projects.scpr.org"
  - name: newsroom
    run_list:
      - recipe[scpr-apps::default]
    attributes:
      consul:
        service_mode: bootstrap
      scpr_apps:
        config:
          newsroom:
            test:
              roles:    ['web']
              hostname: "newsroom.scprdev.org"
