---
driver:
  name: docker
  use_sudo: false
  privileged: true
  username: kitchen
  provision_command: mkdir -p /run/sshd

provisioner:
  product_name: chef
  product_version: 12


platforms:
  - name: ubuntu-12.04
  - name: ubuntu-18.04

suites:
  - name: scprv4
    run_list:
      - recipe[scpr-apps::default]
    attributes:
      consul:
        service_mode: bootstrap
      scpr_apps:
        nfs_enabled: false
        config:
          scprv4:
            test:
              roles:    ['web','worker']
              hostname: scprv4.kitchen
  - name: streammachine
    run_list:
      - recipe[scpr-apps::default]
    attributes:
      consul:
        service_mode: bootstrap
      ffmpeg:
        git_repository: https://github.com/FFmpeg/FFmpeg.git
      scpr_apps:
        config:
          streammachine:
            test:
              roles:    ['standalone']
  - name: projects
    run_list:
      - recipe[scpr-apps::default]
    attributes:
      consul:
        service_mode: bootstrap
      scpr_apps:
        config:
          projects:
            test:
              roles:    ['web']
              hostname: "projects.scpr.org"
  - name: newsroom
    run_list:
      - recipe[scpr-apps::default]
    attributes:
      consul:
        service_mode: bootstrap
      scpr_apps:
        config:
          newsroom:
            test:
              roles:    ['web']
              hostname: "newsroom.scprdev.org"
  - name: jruby
    run_list:
      - recipe[scpr-apps-test::jruby]
